### ISSUE TITLE
Crash on RangeError: Attempt to access memory outside buffer bounds

### ISSUE THREAD

**Issue by vladimir-krasulya2** [SidOfc/leather#27]
Sometimes it crash on trying to determine resolution on buffer (quite hard to reproduce)
```
RangeError: Attempt to access memory outside buffer bounds
    at new NodeError (node:internal/errors:405:5)
    at boundsError (node:internal/buffer:86:11)
    at Buffer.readUInt8 (node:internal/buffer:254:5)
    at readMediaAttributes (/app/dist/apps/api/node_modules/leather/dist/extractors/jpg.cjs:20:29)
    at readMediaAttributes (/app/dist/apps/api/node_modules/leather/dist/index.cjs:66:40)
```
it's crashing on this line https://github.com/SidOfc/leather/blob/master/src/extractors/jpg.js#L18
I guess its because sometimes buffer size is smaller then its expected in the code and we need additional check

**Comment by SidOfc** [comment]
Hmn this should be consistently reproducible with the same file, is this not the case?

**Comment by vladimir-krasulya2** [comment]
I'm using Buffer (trying to determine dimensions from incoming stream and not download a file entirely)

**Comment by SidOfc** [comment]
I see, could you convert one buffer which errors out to a file and upload it here? Or otherwise provide a repro?

**Comment by vladimir-krasulya2** [comment]
Here is an example:
I've added `data?.subarray(0, 210)` to simulate the case when chunk is small enough to cause the error (most of the time chunk is 16kb and this is why its hard to reproduce)
```
const { readMediaAttributes } = require('leather');
const axios = require('axios');


function getMediaDimensionsByUrl(url) {
  return new Promise((resolve, reject) => { (async () => {
    const { data: stream } = await axios.get(url, { responseType: 'stream' });

    let data;
    stream.on('data', chunk => {
      data = data ? Buffer.concat([data, chunk]) : chunk;

      const mediaAttr = readMediaAttributes(data?.subarray(0, 210));

      if (!mediaAttr.width && !mediaAttr.height) return;
      resolve(mediaAttr);
    });

    stream.on('error', reject);
  })()});
}

getMediaDimensionsByUrl('https://d33czfmi72yk6o.cloudfront.net/0fdbc22e-9b8e-4c42-821b-197b13285bb1/https:/d33czfmi72yk6o.cloudfront.net/0fdbc22e-9b8e-4c42-821b-197b13285bb1/https:/api-www.louvre.fr/sites/default/files/styles/w1465_h628_c1/public/2021-05/leonard-de-vinci-la-joconde-portrait-de-monna-lisa-detail-du-visage.jpg').then(console.log);
```

**Comment by SidOfc** [comment]
I'll take a look at it later today, cheers for the report 👍

**Comment by SidOfc** [comment]
Hmn just looking at this again and noticed a different problem which I think will require a fair amount of extra work to make this work properly. The thing is that `readMediaAttributes` uses the first bytes in given `input` (the buffer in your case) to identify which extractor to use.

As you can imagine, after the initial bytes have been processed the first time around and no dimensions are found, when you then try to feed it the second chunk `readMediaAttributes` will again attempt to figure out which extractor to use and will likely fail because it's already past the start of the actual file.

This plugin really isn't made for processing "parts" of data in this way. Rather a complete file or a buffer in which dimensions are already present is expected to be given. When streaming this process becomes rather unpredictable meaning that code must be implemented to ensure that "pauses" execution / reading until more data has been fed.

 This would require more of a full rewrite even to support since a number of extractors loop until the file / buffer is empty, reading chunks of specific sizes based on known file structure at once.
 
 As for your specific scenario it does fail in the jpg extractor. This is because the first chunk is already "too small" and runs into the issue of wanting to read a chunk of a specific size but it can't since only a part of the chunk is there.
 
There is no way I'm going to be able to fix this properly anytime soon. Instead of feeding parts of the buffer to `readMediaAttributes` I would instead try one of the following:

- Collect the entire image in the buffer and then pass it to `readMediaAttributes`
- Collect a "big enough" (say 4KB of data) buffer and pass that to `readMediaAttributes`

The latter option will allow retaining some gains when images are quite large (1MB+) but can actually still fail if dimensions are near the end of the file (which shouldn't be the case in any format).

**EDIT:** Fixed some typos

**Comment by vladimir-krasulya2** [comment]
ok, second option should work for me , thx in advice 👍

**Comment by SidOfc** [comment]
I'll leave it open for now as I might consider this at some point

**Comment by SidOfc** [comment]
I've given streams a real shot but due to their asynchronous nature everything became promisified which incurred a severe performance penalty (~9x slower).

Because of this I won't be looking into this idea anymore and will close this issue.
Thanks for the interesting use-case! 👍 

**EDIT:** Actually the performance penalty is only ~3x slower, node caching file contents did a number on me here, still significant enough to leave it alone I think.
